### ISSUE TITLE
Audio Unit fails to initialize in Logic Pro X on Mojave

### ISSUE THREAD

**Issue by MC242** [rudeog/stochas_open#1]
As the topic says, I can't get Stochas to validate in latest Logic Pro X on mac OS Mojave.

**Comment by MC242** [comment]
VST3 fails to load, too by the way.

**Comment by rudeog** [comment]
Hi, unfortunately I only have Catalina (and a really old mac with El Capitan which I have not even tested). For the VST3 is there any way to tell why it's not loading? (eg some diagnostic messages) Are you in a position where you might be able to try to do a build on Mojave? It would mean installing a few dev tools though. I will ask on the JUCE forum to see if anything special needs to be done for Mojave when building from Catalina

**Comment by MC242** [comment]
Unfortunately I have no programming skills. I'm only on Github as a program user. :) 

Here are some hints from the console:

Error loading /Library/Audio/Plug-Ins/VST3/Stochas.vst3/Contents/MacOS/Stochas:  dlopen(/Library/Audio/Plug-Ins/VST3/Stochas.vst3/Contents/MacOS/Stochas, 262): Symbol not found: _objc_opt_class
  Referenced from: /Library/Audio/Plug-Ins/VST3/Stochas.vst3/Contents/MacOS/Stochas (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /Library/Audio/Plug-Ins/VST3/Stochas.vst3/Contents/MacOS/Stochas

Hopefully they will help you!

**Comment by rudeog** [comment]
Yes that error message may help. I've put out a question on JUCE forum. If I can make any headway with this, I will try to put together a new binary for you to test.

**Comment by rudeog** [comment]
Can you try (if you are willing) to download this:
https://drive.google.com/file/d/14zj0dMESfhvcfv_-tDKeHEm_PMPEaTYK/view?usp=sharing
It's a zip file which you'd need to unzip into your VST3 folder. I've built the library on my old El Capitan mac and would like to see if it runs on your system.

**Comment by MC242** [comment]
Thank you! This VST3 now runs fine. :) Great!
Unfortunately my main daw is Logic Pro X, so I would need an Audio Unit mainly. :/

**Comment by rudeog** [comment]
Ok, I've built a new 1.3.2 package. See if the Audio Unit works ok now.

**Comment by MC242** [comment]
Yes, the Audio Unit works now! Thank you!
But now I have another problem.
The Audio Unit was a Midi FX AUMF format before.
Now it is in AU instrument format.
Audio Unit instruments are for plugins that have an own sound engine.
But Stochas is only Midi and needs an instrument to be chained after it.
This would only work if it was an AUMFX.

**Comment by rudeog** [comment]
Ok. The settings in the new style of building (cmake with juce 6) are different than in the old setup. I've flipped it to midi effect and done a test build here. https://drive.google.com/file/d/1Sixd3M-uLu5_1O4vEsdVU42Kmw1FAAmz/view?usp=sharing
If you could give it a try and let me know whether it's correct (I don't have Logic). If so, I'll need to figure out how to automate it properly. If still not right, let me know and I'll see what I can do. Thanks for testing.

**Comment by MC242** [comment]
Excellent! Now it is working like it's supposed to be in Logic Pro X! 
Thank you for fixing!!

**Comment by rudeog** [comment]
Awesome.
