### ISSUE TITLE
VST2 environment not passing

### ISSUE THREAD

**Issue by tank-trax** [rudeog/stochas_open#6]
this change to CMakeLists.txt
```
if (DEFINED ${VST2_PATH})
  message("Building VST2. SDK at ${VST2_PATH}")
  juce_set_vst2_sdk_path(${VST2_PATH})
  set(VST2 "VST")
endif()
```

from the previous

```
if (DEFINED ENV{VST2_PATH})
  juce_set_vst2_sdk_path($ENV{VST2_PATH})
  set(VST2 "VST")
endif()
```

made it so that the VST2 did not build without the ENV variable

**Comment by rudeog** [comment]
Hi, what about if you build with cmake -B build -DVST2_PATH=<path> ?
Or is that considered non-standard?

**Comment by tank-trax** [comment]
I tried both

`export VST2_PATH=/path/to/VST2_SDK` 

and

`cmake --build build --config Release -DVST2_PATH=/path/to/VST2_SDK`

with the `if (DEFINED ${VST2_PATH})` and neither built the VST2

the VST2 only built when using `if (DEFINED ENV{VST2_PATH})`

**Comment by rudeog** [comment]
What about passing it during the configure step (ie cmake -B build -DVST2_PATH=) ?
If it's not practical to do it during that step, it's fine, I just want to try to understand...

**Comment by tank-trax** [comment]
my apologies in that last comment, it was in the configure step that I tried the `-DVST2_PATH`

`cmake -Bbuild -DVST2_PATH=/path/to/VST2_SDK`
or
`cmake -B build -DVST2_PATH=/path/to/VST2_SDK`

only creates the VST3 and Standalone

also, if I use   `cmake -B build -DVST2_PATH=/path/to/VST2_SDK` with the previous `if (DEFINED ENV{VST2_PATH})`
it will return
```
Manually-specified variables were not used by the project:

    VST2_PATH
```

**Comment by tank-trax** [comment]
I found it, to get

`cmake -Bbuildvst2 -DVST2_PATH=/path/to/VST2_SDK`

to get the variable

change 

`if (DEFINED ${VST2_PATH})`

to

`if (VST2_PATH)`

**Comment by rudeog** [comment]
Try change it to:

if (DEFINED VST2_PATH)

and then run 
cmake -Bbuildvst2 -DVST2_PATH=/path/to/VST2_SDK

and let me know if it works

**Comment by tank-trax** [comment]
yes, that most certainly did work, the variable was passed and VST, VST3 and Standalone all built

the VST however is named **libStochas.so** (this is on Linux Debian Buster, not sure about the naming convention on MAC and WIN)

the VST3 is **Stochas.so**
Standalone is **Stochas**

**Comment by rudeog** [comment]
Thanks. I will fix the script. I am going to close this issue. Any other ones should be opened on the new main repo at https://github.com/surge-synthesizer/stochas
