### ISSUE TITLE
question on distribution format (DLL in ZIP)

### ISSUE THREAD

**Issue by firolightfog** [rudeog/stochas_open#7]
Hi,
A silly question on the distribution format: could you please make a ZIPped DLL available? 
Having trouble with system rights at installing with the setup EXE here. {:~]
Best regards,

**Comment by rudeog** [comment]
Hi, there is a zip available at the new repo which is https://github.com/surge-synthesizer/stochas
Look under releases under assets. Any new issues should be opened in that repo.
