### ISSUE TITLE
AU plugin could not be validated in Logic Pro X 10.4.8

### ISSUE THREAD

**Issue by Colliwomple** [rudeog/stochas_open#8]
When i try to validate it with the plugin manager i get
" validating Audio Unit Stochas by Audio Vitamins:

validation result: Validierung erfolgreich

updating properties of AU Stochas by Audio Vitamins…FAILED! "
When try to opening the plugin i get " Can´t load ..... contact developer"
OSX Version 10.14.5
Tried it with version 1.3.1 and 1.3.2... can`t validate

**Comment by rudeog** [comment]
Hi Colliwomple,
Can you try to get the release version from https://github.com/surge-synthesizer/stochas 
v1.3.3 is the version on that page.
If it still fails to validate, can you open an issue on that page. This page that you are on is not supported anymore and is going away.
